# Generated by Django 4.2 on 2023-05-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeeseohyun', '0002_blog_wrtier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='wrtier',
            new_name='writer',
        ),
    ]
